version: "3.3"

services:
  ess-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ess-backend
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/usr/src/app/backend
    networks:
      - api-network
    environment:
      DB_URL: ${DB_URL}

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - api-network
    env_file:
      - ./.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_URL=${DB_URL}

networks:
  api-network:
    driver: overlay
    attachable: true

volumes:
  mongodb-data: